source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# Use jquery as the JavaScript library
gem 'jquery-rails'
# https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# The gem we're building
gem 'bootswatch-sass', :path => File.expand_path('../../../', __FILE__)

# Some development goodies
group :development, :test do
  # Binding of caller
  gem 'binding_of_caller'
  # Better errors
  gem 'better_errors'
  # Awesome print
  gem 'awesome_print'
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console'
end
